/*
 * mvn generated by tentackle-project-archetype.
 */

package flipkart.pdo.md;

import flipkart.pdo.MasterData;
import flipkart.pdo.md.domain.OrgUnitDomain;
import flipkart.pdo.md.persist.OrgUnitPersistence;

import org.tentackle.pdo.Plural;
import org.tentackle.pdo.Singular;
import org.tentackle.session.TableName;

/*
 * @{
 * tablename = md.orgunit
 * mapping   = $model/$tablename.map
 * @}
 */

/*
 * @> $mapping
 *
 * # Organizational Unit
 * name := $classname
 * table := $tablename
 * inheritance := multi
 * integrity := $integrity
 *
 * ## attributes
 * [cached | +name]
 * String($ou_name)       name        name        short name [key, uc, normtext]
 * String($ou_comment)    comment     ocomment    optional comment [normtext]
 *
 * ## indexes
 * unique index udk := name
 *
 * ## relations
 *
 * ## validations
 * name: @NotNull(message="{ @('please enter the name') }")
 *
 * @<
 */

/**
 * Organizational Unit.
 * <p>
 * Base entity for organizational units.
 *
 * @param <T> the orgunit type
 */
@TableName(value =/**/"md.orgunit"/**/, // @wurblet < Inject --string $tablename
           mapSchema =/**/false/**/,    // @wurblet < Inject $mapSchema
           prefix =/**/""/**/)          // @wurblet < Inject --string $tablePrefix
@Singular("Organizational Unit")
@Plural("Organizational Units")
public interface OrgUnit<T extends OrgUnit<T>> extends MasterData<T>, OrgUnitPersistence<T>, OrgUnitDomain<T> {

  // @wurblet(fold=expanded) modelComment ModelComment

  //<editor-fold defaultstate="expanded" desc="code 'modelComment' generated by wurblet ModelComment">//GEN-BEGIN:modelComment

  /*
   * -------------------------------------------------------------------------------------------------------------------
   *
   * OrgUnit is referenced by:
   *
   * Message via orgUnitId as orgUnit [1:1]
   *
   *
   * OrgUnit is a root entity
   *
   *
   * OrgUnit is not referencing other entities
   *
   *
   * Components of OrgUnit are not deeply referenced
   *
   *
   * OrgUnit is extended by:
   *    ^ User
   *    ^ UserGroup
   *
   * -------------------------------------------------------------------------------------------------------------------
   */

  //</editor-fold>//GEN-END:modelComment


  // @wurblet uniqueDomainKey UniqueDomainKey

  //<editor-fold defaultstate="collapsed" desc="code 'uniqueDomainKey' generated by wurblet UniqueDomainKey">//GEN-BEGIN:uniqueDomainKey

  // unique domain key for OrgUnit is name

  //</editor-fold>//GEN-END:uniqueDomainKey

}
