/*
 * mvn generated by tentackle-project-archetype.
 */

package flipkart.pdo.md;

import flipkart.pdo.MasterData;
import flipkart.pdo.md.domain.User2GroupDomain;
import flipkart.pdo.md.persist.User2GroupPersistence;

import org.tentackle.pdo.Plural;
import org.tentackle.pdo.Singular;
import org.tentackle.session.ClassId;
import org.tentackle.session.TableName;

/*
 * @{
 * tablename = md.user2group
 * classid   = 1003
 * mapping   = $model/$tablename.map
 * @}
 */

/*
 * @> $mapping
 *
 * # User to Group N:M Link
 * name := $classname
 * table := $tablename
 * id := $classid
 * integrity := $integrity
 *
 * ## attributes[-bind, -autoselect, -size]
 * long     userGroupId     group_id    user group ID
 * long    	userId          user_id     user ID
 *
 * ## indexes
 * unique index udk := group_id, user_id
 * index user       := user_id
 *
 * ## relations
 * User:
 *    select = cached
 *
 * UserGroup:
 *    select = cached
 *
 * ## validations
 *
 * @<
 */

/**
 * User to Group N:M Link.
 * <p>
 * NM-relation link between user and usergroup
 */
@TableName(value =/**/"md.user2group"/**/, // @wurblet < Inject --string $tablename
           mapSchema =/**/false/**/,       // @wurblet < Inject $mapSchema
           prefix =/**/""/**/)             // @wurblet < Inject --string $tablePrefix
@ClassId(/**/1003/**/)                     // @wurblet < Inject $classid
@Singular("User2Group")
@Plural("User2Groups")
public interface User2Group extends MasterData<User2Group>, User2GroupPersistence, User2GroupDomain {

  // @wurblet(fold=expanded) modelComment ModelComment

  //<editor-fold defaultstate="expanded" desc="code 'modelComment' generated by wurblet ModelComment">//GEN-BEGIN:modelComment

  /*
   * -------------------------------------------------------------------------------------------------------------------
   *
   * User2Group is referenced by:
   *
   * User via u2g.userId as nmLinks [1:N]
   * UserGroup via u2g.userGroupId as nmLinks [1:N]
   *
   *
   * User2Group is referencing the following entities:
   *
   * User via userId [1:1]
   * UserGroup via userGroupId [1:1]
   *
   *
   * User2Group is a component of: User, UserGroup
   * and belongs to the root entities: User, UserGroup
   *
   *
   * User2Group is not extended
   *
   * -------------------------------------------------------------------------------------------------------------------
   */

  //</editor-fold>//GEN-END:modelComment


  // @wurblet uniqueDomainKey UniqueDomainKey

  //<editor-fold defaultstate="collapsed" desc="code 'uniqueDomainKey' generated by wurblet UniqueDomainKey">//GEN-BEGIN:uniqueDomainKey

  // User2Group is not a root entity

  //</editor-fold>//GEN-END:uniqueDomainKey

}
