/*
 * mvn generated by tentackle-project-archetype.
 */

package flipkart.pdo.md;

import flipkart.pdo.md.domain.UserDomain;
import flipkart.pdo.md.persist.UserPersistence;

import org.tentackle.pdo.Plural;
import org.tentackle.pdo.Singular;
import org.tentackle.session.ClassId;
import org.tentackle.session.TableName;

/*
 * @{
 * tablename = md.user
 * classid   = 1001
 * mapping   = $model/$tablename.map
 * @}
 */

/*
 * @> $mapping
 *
 * # User
 * name := $classname
 * table := $tablename
 * id := $classid
 * extends := OrgUnit
 * integrity := $integrity
 *
 * ## attributes
 * [cached]
 * String(64)   password                      password        hashed password [MUTE]
 * boolean      loginAllowed                  login_allowed   true if login is allowed
 * boolean      passwordChangeable            passwd_chgbl    user allowed to change its own password?
 * boolean      changingPreferencesAllowed	  prefs_chgbl     user allowed to maintain its own preferences?
 * boolean      systemPreferencesOnly         prefs_system    user restricted to system preferences only?
 *
 * ## indexes
 *
 * ## relations
 * User2Group:
 *    relation = composite list,
 *    name = nmLinks,
 *    method = UserId,
 *    nm = UserGroup UserGroups
 *
 * ## validations
 *
 * @<
 */

/**
 * Organizational Unit User.
 * <p>
 * For security reasons, the password hash is stored in the user table, but is not part of the User PDO.
 */
@TableName(value =/**/"md.user"/**/, // @wurblet < Inject --string $tablename
           mapSchema =/**/false/**/, // @wurblet < Inject $mapSchema
           prefix =/**/""/**/)       // @wurblet < Inject --string $tablePrefix
@ClassId(/**/1001/**/)               // @wurblet < Inject $classid
@Singular("User")
@Plural("Users")
public interface User extends OrgUnit<User>, UserPersistence, UserDomain {

  // @wurblet(fold=expanded) modelComment ModelComment

  //<editor-fold defaultstate="expanded" desc="code 'modelComment' generated by wurblet ModelComment">//GEN-BEGIN:modelComment

  /*
   * -------------------------------------------------------------------------------------------------------------------
   *
   * User is referenced by:
   *
   * Message via orgUnitId as orgUnit [1:1]
   * UserGroup via User2Group as NmLinks [N:M]
   *
   *
   * User is a root entity
   *
   *
   * User is a composite with the components:
   *    + User2Group via u2g.userId as nmLinks [N:M] to UserGroup as userGroups
   *
   *
   * User is referencing the following entities:
   *
   * UserGroup from User2Group via userGroupId [N:M]
   *
   *
   * Components of User are not deeply referenced
   *
   *
   * User is not extended
   *
   * -------------------------------------------------------------------------------------------------------------------
   */

  //</editor-fold>//GEN-END:modelComment


  // @wurblet uniqueDomainKey UniqueDomainKey

  //<editor-fold defaultstate="collapsed" desc="code 'uniqueDomainKey' generated by wurblet UniqueDomainKey">//GEN-BEGIN:uniqueDomainKey

  // User inherits from OrgUnit

  //</editor-fold>//GEN-END:uniqueDomainKey

}
