/*
 * mvn generated by tentackle-project-archetype.
 */

package flipkart.pdo;

import org.reflections.Reflections;
import org.testng.Assert;
import org.testng.Reporter;
import org.testng.annotations.Test;

import java.util.MissingResourceException;

/**
 * Tests the translations for enums.<br>
 * Those are not covered by the tentackle-check:bundles mojo because the parameter
 * of getString is not a literal.
 */
public class EnumI18nTest {

  @Test
  public void testEnums() {
    Reflections reflections = new Reflections("flipkart");
    reflections.getSubTypesOf(Enum.class).forEach(c -> {
      Reporter.log("enum " + c.getName() + "<br>");
      for (Object constant: c.getEnumConstants()) {
        try {
          Reporter.log(constant.toString() + "<br>");    // this will use the bundle
        }
        catch (MissingResourceException mx) {
          Assert.fail("missing resource for " + c.getName() + ": " + mx.getMessage());
        }
      }
    });
  }

}
