/*
 * mvn generated by tentackle-project-archetype.
 */

package flipkart.gui.user;

import flipkart.gui.GuiBundle;
import flipkart.gui.GuiConstants;
import flipkart.pdo.md.User;
import flipkart.pdo.md.UserGroup;
import javafx.collections.ObservableList;
import javafx.scene.control.MenuItem;
import javafx.scene.control.TreeItem;

import org.tentackle.fx.Fx;
import org.tentackle.fx.rdc.PdoTreeCell;
import org.tentackle.fx.rdc.PdoTreeContextMenuItem;
import org.tentackle.fx.rdc.PdoTreeContextMenuItemService;

/**
 * Menu item to remove a usergroup from a user.
 */
@PdoTreeContextMenuItemService(value = UserGroup.class, ordinal = 500, group = GuiConstants.ITEM_GROUP)
public class RemoveUserGroupItem extends MenuItem implements PdoTreeContextMenuItem<UserGroup> {

  /**
   * Creates a menu item.
   *
   * @param cell the tree cell
   */
  public RemoveUserGroupItem(PdoTreeCell<UserGroup> cell) {
    super(GuiBundle.getString("remove from user"), Fx.createImageView("cut"));
    UserGroup group = cell.getItem();
    boolean disabled = true;
    if (group.isEditAllowed()) {
      User user = cell.getPdoTreeItem().getParentPdo(User.class);
      if (user != null) {
        disabled = false;
        setOnAction(e -> {
          user.getUserGroups().remove(group);
          user.save();
          @SuppressWarnings("unchecked")
          ObservableList<TreeItem<UserGroup>> items = (ObservableList) cell.getPdoTreeItem().getParentPdoItem().getChildren();
          int i=0;
          for (TreeItem<UserGroup> item: items) {
            if (group.equals(item.getValue())) {
              items.remove(i);
              cell.getTreeView().refresh();
              break;
            }
            i++;
          }
        });
      }
    }
    setDisable(disabled);
  }

}
