/*
 * mvn generated by tentackle-project-archetype.
 */

package flipkart.gui.user;

import flipkart.gui.password.ChangePasswordView;
import flipkart.pdo.md.User;
import flipkart.pdo.md.UserGroup;
import javafx.collections.transformation.SortedList;
import javafx.fxml.FXML;
import javafx.scene.control.ContextMenu;
import javafx.scene.control.Label;
import javafx.scene.control.MenuItem;
import javafx.scene.control.TableRow;
import javafx.stage.Modality;

import org.tentackle.bind.Bindable;
import org.tentackle.fx.FxControllerService;
import org.tentackle.fx.component.FxButton;
import org.tentackle.fx.component.FxCheckBox;
import org.tentackle.fx.component.FxTableView;
import org.tentackle.fx.component.FxTextArea;
import org.tentackle.fx.component.FxTextField;
import org.tentackle.fx.rdc.PdoEditor;
import org.tentackle.fx.rdc.Rdc;
import org.tentackle.fx.rdc.RdcFactory;
import org.tentackle.fx.rdc.table.TablePopup;
import org.tentackle.pdo.DomainContext;
import org.tentackle.pdo.Pdo;

import java.util.List;
import java.util.ResourceBundle;



/**
 * Editor for User.
 */
@FxControllerService
public class UserEditor extends PdoEditor<User> {

  @Bindable
  private User user;

  @FXML
  private FxTextField userNameField;

  @FXML
  private FxTextArea userCommentField;

  @FXML
  private FxButton passwordButton;

  @FXML
  private FxCheckBox userLoginAllowedField;

  @FXML
  private FxCheckBox userPasswordChangeableField;

  @FXML
  private FxCheckBox userChangingPreferencesAllowedField;

  @FXML
  private FxCheckBox userSystemPreferencesOnlyField;

  @FXML
  private FxTableView<UserGroup> userUserGroupsNode;

  @FXML
  private ResourceBundle resources;

  private TablePopup<UserGroup> popup;


  @FXML
  private void initialize() {
    userUserGroupsNode.setRowFactory(t -> {
      TableRow<UserGroup> row = new TableRow<>();
      row.setContextMenu(createContextMenu(row));
      return row;
    });
    Label emptyLabel = new Label(resources.getString("no groups"));
    emptyLabel.setContextMenu(createContextMenu(null));
    userUserGroupsNode.setPlaceholder(emptyLabel);

    popup = RdcFactory.getInstance().createTablePopup(userUserGroupsNode, "UserEditor", resources.getString("Groups"));
  }

  @Override
  public User getPdo() {
    return user;
  }

  @Override
  public void setPdo(User pdo) {
    user = pdo;
    getBinder().putBindingProperty(DomainContext.class, pdo.getDomainContext());
  }

  @Override
  public void setChangeable(boolean changeable) {
    super.setChangeable(changeable);
    passwordButton.setDisable(!changeable || user.isNew() || !user.isEditAllowed());
  }

  @Override
  public void requestInitialFocus() {
    userNameField.requestFocus();
  }

  @Override
  public void configure() {
    popup.loadPreferences();
    passwordButton.setOnAction(event -> ChangePasswordView.showDialog(user));
  }


  @SuppressWarnings("unchecked")
  private ContextMenu createContextMenu(TableRow<UserGroup> row) {
    ContextMenu contextMenu = new ContextMenu();

    MenuItem addMenuItem = new MenuItem(resources.getString("add group to user"));
    addMenuItem.setOnAction(e -> {
      Rdc.displaySearchStage(
          Pdo.create(UserGroup.class, getBinder().getBindingProperty(DomainContext.class)),
          Modality.APPLICATION_MODAL, getStage(), true, groups -> {
            if (!groups.isEmpty()) {
              UserGroup group = groups.get(0);
              if (!userUserGroupsNode.getItems().contains(group)) {
                ((List<UserGroup>) ((SortedList<UserGroup>) userUserGroupsNode.getItems()).getSource()).add(group);
                userUserGroupsNode.triggerViewModified();
              }
            }
          });
    });
    contextMenu.getItems().add(addMenuItem);

    if (row != null) {
      MenuItem removeMenuItem = new MenuItem(resources.getString("remove group from user"));
      removeMenuItem.disableProperty().bind(row.emptyProperty());
      removeMenuItem.setOnAction(e -> {
        ((SortedList<UserGroup>) userUserGroupsNode.getItems()).getSource().remove(row.getItem());
        userUserGroupsNode.triggerViewModified();
      });
      contextMenu.getItems().add(removeMenuItem);
    }

    return contextMenu;
  }

}
