/*
 * mvn generated by tentackle-project-archetype.
 */

package flipkart.gui.main;

import flipkart.common.mvnDomainContext;
import flipkart.common.mvnPreferences;
import flipkart.gui.mvnImageProvider;
import flipkart.gui.about.AboutView;
import flipkart.gui.password.ChangePasswordView;
import flipkart.gui.prefs.PreferencesDialog;
import flipkart.pdo.md.User;
import flipkart.pdo.md.UserGroup;
import flipkart.pdo.td.Message;
import javafx.application.Platform;
import javafx.fxml.FXML;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.MenuItem;
import javafx.scene.image.ImageView;
import javafx.scene.layout.BorderPane;
import javafx.stage.Modality;
import javafx.stage.Stage;

import org.tentackle.app.AbstractApplication;
import org.tentackle.common.StringHelper;
import org.tentackle.common.TentackleRuntimeException;
import org.tentackle.fx.AbstractFxController;
import org.tentackle.fx.Fx;
import org.tentackle.fx.FxControllerService;
import org.tentackle.fx.component.FxButton;
import org.tentackle.fx.rdc.Rdc;
import org.tentackle.fx.rdc.admin.SessionsView;
import org.tentackle.fx.rdc.app.DesktopApplication;
import org.tentackle.fx.rdc.security.SecurityDialogFactory;
import org.tentackle.pdo.AdminExtension;
import org.tentackle.pdo.DomainContextProvider;
import org.tentackle.pdo.PersistentDomainObject;
import org.tentackle.prefs.PersistedPreferencesFactory;
import org.tentackle.security.SecurityFactory;
import org.tentackle.security.pdo.Security;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.util.ResourceBundle;

/**
 * FX main controller.
 */
@FxControllerService
public class MainController extends AbstractFxController implements DomainContextProvider {

  @FXML
  private BorderPane borderPane;

  @FXML
  private MenuItem securityManagerItem;

  @FXML
  private MenuItem sessionsItem;

  @FXML
  private MenuItem preferencesItem;

  @FXML
  private MenuItem passwordItem;

  @FXML
  private MenuItem exitItem;

  @FXML
  private MenuItem editUserItem;

  @FXML
  private MenuItem editUserGroupItem;

  @FXML
  private MenuItem searchUserItem;

  @FXML
  private MenuItem searchUserGroupItem;

  @FXML
  private MenuItem searchMessageItem;

  @FXML
  private MenuItem helpItem;

  @FXML
  private MenuItem aboutItem;

  @FXML
  private ResourceBundle resources;



  @Override
  public mvnDomainContext getDomainContext() {
    return (mvnDomainContext) AbstractApplication.getRunningApplication().getDomainContext();
  }

  @FXML
  public void initialize() {

    ImageView centerImage = Fx.createImageView(mvnImageProvider.REALM, "tentackle");
    borderPane.setCenter(centerImage);

    securityManagerItem.setGraphic(Fx.createImageView("security"));
    securityManagerItem.setDisable(!SecurityDialogFactory.getInstance().isDialogAllowed(getDomainContext()));
    securityManagerItem.setOnAction(e ->
            SecurityDialogFactory.getInstance().showDialog(on(Security.class).getClassId(), getDomainContext()));

    sessionsItem.setGraphic(Fx.createImageView("modem"));
    sessionsItem.setDisable(!SecurityFactory.getInstance().getSecurityManager().evaluate(
        getDomainContext(), SecurityFactory.getInstance().getExecutePermission(), AdminExtension.class).isAccepted());
    sessionsItem.setOnAction(e -> manageSessions());

    preferencesItem.setGraphic(Fx.createImageView("preferences"));
    preferencesItem.setDisable(
            !PersistedPreferencesFactory.getInstance().isSystemOnly() ||
            !SecurityFactory.getInstance().getSecurityManager().evaluate(
                getDomainContext(), SecurityFactory.getInstance().getExecutePermission(), PreferencesDialog.class).isAccepted());
    preferencesItem.setOnAction(e -> PreferencesDialog.show());

    passwordItem.setGraphic(Fx.createImageView("password"));
    passwordItem.setOnAction(e -> ChangePasswordView.showDialog(DesktopApplication.getDesktopApplication().getUser(getDomainContext())));

    exitItem.setGraphic(Fx.createImageView("exit"));
    exitItem.setOnAction(e -> exit());

    editUserItem.setGraphic(Fx.createImageView(mvnImageProvider.REALM, "user"));
    editUserItem.setOnAction(e -> edit(User.class));

    editUserGroupItem.setGraphic(Fx.createImageView(mvnImageProvider.REALM, "usergroup"));
    editUserGroupItem.setOnAction(e -> edit(UserGroup.class));

    searchUserItem.setGraphic(Fx.createImageView(mvnImageProvider.REALM, "user"));
    searchUserItem.setOnAction(e -> search(User.class));

    searchUserGroupItem.setGraphic(Fx.createImageView(mvnImageProvider.REALM, "usergroup"));
    searchUserGroupItem.setOnAction(e -> search(UserGroup.class));

    searchMessageItem.setGraphic(Fx.createImageView(mvnImageProvider.REALM, "message"));
    searchMessageItem.setOnAction(e -> search(Message.class));

    helpItem.setGraphic(Fx.createImageView("help"));
    helpItem.setOnAction(e -> help());

    aboutItem.setGraphic(Fx.createImageView("about"));
    aboutItem.setOnAction(e -> AboutView.showDialog());
  }


  /**
   * Asks the user whether to exit the application and does so if yes.
   */
  public void exit() {
    Fx.yes(resources.getString("ExitAction"), false, Platform::exit);
  }


  /**
   * Shows the edit dialog for given PDO-class.
   *
   * @param <T> the pdo type
   * @param clazz the pdo class
   */
  private <T extends PersistentDomainObject<T>> void edit(Class<T> clazz) {
    Rdc.displayCrudStage(on(clazz), true, Fx.getStage(getView()));
  }

  /**
   * Shows the search dialog for given PDO-class.
   *
   * @param <T> the pdo type
   * @param clazz the pdo class
   */
  private <T extends PersistentDomainObject<T>> void search(Class<T> clazz) {
    Rdc.displaySearchStage(on(clazz), Fx.getStage(getView()), false);
  }


  /**
   * Shows the help browser.
   */
  private void help() {
    String helpUrl = mvnPreferences.getInstance().getHelpUrl();
    if (StringHelper.isAllWhitespace(helpUrl)) {
      Fx.info("Help URL not configured. Please edit the Preferences!");
    }
    else {
      // extra thread because Desktop blocks FX thread
      new Thread(() -> {
        try {
          Desktop.getDesktop().browse(URI.create(helpUrl));
        }
        catch (IOException ex) {
          throw new TentackleRuntimeException("could not open online help", ex);
        }
      }).start();
    }
  }


  /**
   * Manages server sessions.
   */
  private void manageSessions() {
    Stage stage = Fx.createStage(Modality.APPLICATION_MODAL);
    SessionsView controller = Fx.load(SessionsView.class);
    FxButton closeButton = Fx.createNode(Button.class);
    closeButton.setText(resources.getString("close"));
    closeButton.setGraphic(Fx.createImageView("close"));
    closeButton.setOnAction(e -> stage.close());
    controller.getButtonBox().getChildren().add(closeButton);
    Scene scene = new Scene(controller.getView());
    stage.setScene(scene);
    stage.setTitle(resources.getString("Sessions"));
    stage.show();
  }

}
