/*
 * mvn generated by tentackle-project-archetype.
 */

/**
 * Middle tier server module.
 */
module flipkart.server {
  exports flipkart.server;
  exports flipkart.server.rmi;

  requires flipkart.persist;
  requires flipkart.domain;

  requires java.rmi;
  requires java.prefs;

  requires org.tentackle.update;

  provides org.tentackle.common.ModuleHook with flipkart.server.service.Hook;

  // SLF4J isnt a module yet. For some odd reason, we need a lookup scan for deps on the classpath.
  // Otherwise non-modularized deps cannot be located via META-INF/services.
  uses org.tentackle.log.Logger;
}