/*
 * mvn generated by tentackle-project-archetype.
 */

package flipkart.common;

/**
 * Application specific constants.
 */
public class Constants {

  /**
   * Number pool realm of mvn.
   */
  public static final String POOL_REALM = "mvn";

  private Constants() {}
}
