/*
 * mvn generated by tentackle-project-archetype.
 */

package flipkart.common;

import org.tentackle.common.Cryptor;
import org.tentackle.common.Service;

/**
 * Application specific en/decryptor.
 */
@Service(Cryptor.class)
public class mvnCryptor extends Cryptor {

  // just to make it a little harder...
  private static byte[] getSalt() {
    byte[] salt = new byte[4];
    salt[1] = 'E';
    salt[0] = 'D';
    salt[3] = 'O';
    salt[2] = 'M';
    return salt;
  }

  // IMPORTANT: the passphrase should *NOT* be part of the application!
  // get it from manual input, mounted USB-stick, whatever...
  private static char[] getPassphrase() {
    char[] passphrase = new char[10];
    passphrase[1] = 'i';
    passphrase[0] = 'D';
    passphrase[6] = 'e';
    passphrase[7] = 'l';
    passphrase[3] = 'o';
    passphrase[2] = 'D';
    passphrase[4] = 'e';
    passphrase[5] = 'd';
    passphrase[9] = 'u';
    passphrase[8] = 'D';
    return passphrase;
  }

  /**
   * Creates the application specific password cryptor.
   */
  public mvnCryptor() {
    super(getSalt(), getPassphrase());
  }
}