/*
 * mvn generated by tentackle-project-archetype.
 */

package flipkart.common;

import org.tentackle.pdo.DefaultDomainContext;
import org.tentackle.session.Session;

/**
 * Application specific domain context.
 */
public class mvnDomainContext extends DefaultDomainContext {

  private static final long serialVersionUID = 1L;

  /**
   * Creates a domain context.
   *
   * @param session the session
   * @param sessionImmutable true if session cannot be changed anymore
   */
  public mvnDomainContext(Session session, boolean sessionImmutable) {
    super(session, sessionImmutable);
  }

  /**
   * Creates a mutable domain context.
   *
   * @param session the session
   */
  public mvnDomainContext(Session session) {
    super(session);
  }

}
