/*
 * mvn generated by tentackle-project-archetype.
 */

package flipkart.common;

import org.tentackle.common.Service;
import org.tentackle.pdo.DomainContext;
import org.tentackle.pdo.DomainContextFactory;
import org.tentackle.session.Session;

/**
 * Application specific domain context factory.
 */
@Service(DomainContextFactory.class)
public class mvnDomainContextFactory implements DomainContextFactory {

  @Override
  public DomainContext create(Session session) {
    return new mvnDomainContext(session);
  }

  @Override
  public DomainContext create(Session session, boolean sessionImmutable) {
    return new mvnDomainContext(session, sessionImmutable);
  }

}
