/*
 * mvn generated by tentackle-project-archetype.
 */

package flipkart.common;

import org.tentackle.bind.Bindable;
import org.tentackle.common.Service;
import org.tentackle.common.ServiceFactory;
import org.tentackle.prefs.CompositePreferences;
import org.tentackle.prefs.PersistedPreferencesFactory;


interface mvnPreferencesHolder {
  mvnPreferences INSTANCE = ServiceFactory.createService(mvnPreferences.class);
}

/**
 * Preferences for mvn.
 */
@Service(mvnPreferences.class)    // defaults to self
public class mvnPreferences extends CompositePreferences {


  /** online help prefix. */
  public static final String HELP_URL = "helpURL";



  public mvnPreferences() {
    super(PersistedPreferencesFactory.getInstance().isSystemOnly());
  }

  /**
   * The singleton.
   *
   * @return the singleton
   */
  public static mvnPreferences getInstance() {
    return mvnPreferencesHolder.INSTANCE;
  }



  @Bindable
  public void setHelpUrl(String val) {
    setString(HELP_URL, val);
  }

  @Bindable
  public String getHelpUrl() {
    return getString(HELP_URL);
  }

}
