/*
 * mvn generated by tentackle-project-archetype.
 */

package flipkart.common;

import org.tentackle.common.Service;
import org.tentackle.session.SessionInfo;
import org.tentackle.session.SessionInfoFactory;

import java.util.Properties;

/**
 * Application specific session info factory.
 */
@Service(SessionInfoFactory.class)
public class mvnSessionInfoFactory implements SessionInfoFactory {

  @Override
  public SessionInfo create(String username, char[] password, String propertiesName) {
    return new mvnSessionInfo(username, password, propertiesName);
  }

  @Override
  public SessionInfo create(String propertiesName) {
    return new mvnSessionInfo(propertiesName);
  }

  @Override
  public SessionInfo create(Properties properties) {
    return new mvnSessionInfo(properties);
  }

  @Override
  public SessionInfo create() {
    return new mvnSessionInfo();
  }

}
