/*
 * mvn generated by tentackle-project-archetype.
 */

package flipkart.pdo.td.domain;

import flipkart.pdo.MessageType;
import flipkart.pdo.md.OrgUnit;
import flipkart.pdo.td.Message;

import org.tentackle.bind.Bindable;
import org.tentackle.pdo.DomainObject;
import org.tentackle.pdo.PersistentDomainObject;
import org.tentackle.pdo.Transaction;

/**
 * Domain interface for Message.
 */
public interface MessageDomain extends DomainObject<Message> {

  /**
   * Creates and persists a message.
   *
   * @param messageType the message type
   * @param refersTo the object the message refers to
   * @param text the message text
   * @param owner the optional owner, null if determine from context
   * @return the persisted message
   */
  @Transaction
  Message create(MessageType messageType, Object refersTo, String text, OrgUnit<?> owner);

  /**
   * Gets the PDO that this message refers to.
   *
   * @return the PDO, null if no PDO referred
   */
  PersistentDomainObject<?> getRefersToPdo();

  /**
   * Gets the formatted string where this message refers to.
   *
   * @return the refers-to
   */
  @Bindable
  String getFormattedRefersTo();

  /**
   * Gets the long diag string.
   *
   * @return the diag string
   */
  String toDiagnosticString();

}
