/*
 * mvn generated by tentackle-project-archetype.
 */

package flipkart.gui;


/**
 * GUI constants.
 */
public class GuiConstants {

  /**
   * The application specific menu items group.
   */
  public static final String ITEM_GROUP = "mvn";

  private GuiConstants() {}
}
