/*
 * mvn generated by tentackle-project-archetype.
 */

package flipkart.gui;

import org.tentackle.fx.DefaultImageProvider;
import org.tentackle.fx.ImageProviderService;

/**
 * Application specific image provider.
 */
@ImageProviderService(mvnImageProvider.REALM)
public class mvnImageProvider extends DefaultImageProvider {

  /**
   * The application's image realm.
   */
  public static final String REALM = "mvn";

}
