/*
 * mvn generated by tentackle-project-archetype.
 */

package flipkart.gui;

import flipkart.pdo.md.OrgUnit;
import flipkart.pdo.md.User;
import flipkart.pdo.md.UserGroup;
import javafx.scene.control.Alert;
import javafx.scene.control.ButtonType;
import javafx.stage.Modality;
import javafx.stage.Window;

import org.tentackle.common.Service;
import org.tentackle.fx.FxFxBundle;
import org.tentackle.fx.rdc.Rdc;
import org.tentackle.fx.rdc.security.DefaultSecurityDialogFactory;
import org.tentackle.fx.rdc.security.SecurityDialogFactory;
import org.tentackle.pdo.DomainContext;
import org.tentackle.pdo.Pdo;
import org.tentackle.pdo.PersistentDomainObject;

import java.util.function.Consumer;

/**
 * Application specific security dialog factory.<br>
 * Implements the selection of the grantee.
 */
@Service(SecurityDialogFactory.class)
@SuppressWarnings("unchecked")        // due to selectGrantee() below
public class mvnSecurityDialogFactory extends DefaultSecurityDialogFactory {

  @Override
  @SuppressWarnings({"rawtypes"})
  public void selectGrantee(Window owner, DomainContext context, Consumer<PersistentDomainObject<?>> grantee) {
    showUserOrGroupDialog(ifUser -> {
      OrgUnit orgUnit = ifUser ? Pdo.create(User.class, context) : Pdo.create(UserGroup.class, context);
      Rdc.displaySearchStage(orgUnit, Modality.APPLICATION_MODAL, owner, false,
                             list -> grantee.accept(list.isEmpty() ? null : list.get(0)));
    });
  }


  /**
   * Shows a question dialog whether to select a user or a group.
   *
   * @param runIt a consumer invoked with true if user, false if group, never null
   */
  public void showUserOrGroupDialog(Consumer<Boolean> runIt) {
    Alert alert = new Alert(Alert.AlertType.CONFIRMATION);
    alert.setTitle(FxFxBundle.getString("QUESTION"));
    alert.setHeaderText(null);
    alert.setContentText(GuiBundle.getString("User or Group?"));
    ButtonType userButtonType = new ButtonType(GuiBundle.getString("User"));
    ButtonType groupButtonType = new ButtonType(GuiBundle.getString("Group"));
    alert.getButtonTypes().setAll(userButtonType, groupButtonType);
    alert.setOnHidden(event -> runIt.accept(alert.getResult() == userButtonType));
    alert.show();
  }

}
