/*
 * mvn generated by tentackle-project-archetype.
 */

package flipkart.pdo;

import org.tentackle.common.Service;
import org.tentackle.pdo.PdoUtilities;

/**
 * Application specific PDO utilities.<br>
 * Extended to translate entity singular and plural.
 */
@Service(PdoUtilities.class)
public class mvnPdoUtilities extends PdoUtilities {

  @Override
  public String getSingular(Class<?> clazz) {
    String singular = super.getSingular(clazz);
    return singular == null ? null : PdoBundle.getString(singular);
  }

  @Override
  public String getPlural(Class<?> clazz) {
    String plural = super.getPlural(clazz);
    return plural == null ? null : PdoBundle.getString(plural);
  }

}
