/*
 * mvn generated by tentackle-project-archetype.
 */

package flipkart.pdo;

import org.tentackle.pdo.PersistentDomainObject;

/**
 * Common PDO interface for transaction data.
 *
 * @param <T> the PDO type
 */
public interface TransactionData<T extends PersistentDomainObject<T>> extends PersistentDomainObject<T> {

}
