/*
 * mvn generated by tentackle-project-archetype.
 */

package flipkart.persist.td.rmi;

import flipkart.pdo.TransactionData;
import flipkart.persist.AbstractPersistentTransactionData;

import org.tentackle.dbms.rmi.RemoteDbSessionImpl;
import org.tentackle.persist.rmi.AbstractPersistentObjectRemoteDelegateImpl;

/**
 * Base implementation for transaction data remote delegates.
 *
 * @param <T> the {@code PersistentDomainObject} class
 * @param <P> the {@code AbstractPersistenObject} class (persistence implementation)
 */
public class AbstractPersistentTransactionDataRemoteDelegateImpl<T extends TransactionData<T>,
                                                                 P extends AbstractPersistentTransactionData<T,P>>
       extends AbstractPersistentObjectRemoteDelegateImpl<T,P> {

  /**
   * Creates a delegate on the serverSession socket.
   *
   * @param serverSession the RMI serverSession
   * @param persistenceClass the subclass of AbstractDbObject
   * @param pdoClass the PDO class (interface)
   */
  public AbstractPersistentTransactionDataRemoteDelegateImpl(RemoteDbSessionImpl serverSession,
                                                             Class<P> persistenceClass, Class<T> pdoClass) {

    super(serverSession, persistenceClass, pdoClass);
  }
}
