/*
 * mvn generated by tentackle-project-archetype.
 */

package flipkart.daemon;

import flipkart.common.Version;
import flipkart.pdo.md.User;
import flipkart.pdo.td.Message;

import org.tentackle.app.ConsoleApplication;
import org.tentackle.log.Logger;
import org.tentackle.pdo.DomainContext;
import org.tentackle.pdo.Pdo;
import org.tentackle.prefs.PersistedPreferencesFactory;
import org.tentackle.session.SessionInfo;


/**
 * Console application for mvn.
 */
@SuppressWarnings("unchecked")    // due to getUser below
public class mvnDaemon extends ConsoleApplication {

  /**
   * the logger for this class.
   */
  private static final Logger LOGGER = Logger.get();

  private long latestMessageId;

  /**
   * Creates the server.
   */
  public mvnDaemon() {
    super("mvnDaemon", Version.RELEASE);
  }

  @Override
  @SuppressWarnings("unchecked")
  public User getUser(DomainContext context, long userId) {
    return Pdo.create(User.class, context).selectCached(userId);
  }

  @Override
  protected void configurePreferences() {
    super.configurePreferences();
    User user = getUser(getDomainContext());    // must exist!
    PersistedPreferencesFactory.getInstance().setSystemOnly(user.isSystemPreferencesOnly());
  }

  @Override
  protected void finishStartup() {
    super.finishStartup();
    latestMessageId = on(Message.class).selectMaxId();
    Pdo.listen(this::logMessages, Message.class);
  }

  private void logMessages() {
    for (Message message : on(Message.class).findLatest(0, latestMessageId)) {
      LOGGER.info("{0}: [{1}|{2}] {3}", message.getWhen(), message.getMessageType(), message.getRefersToText(), message.getText());
      latestMessageId = message.getId();
    }
  }


  /**
   * Starts the daemon.
   *
   * @param args the command line arguments
   */
  public static void main(String[] args) {
    new mvnDaemon().start(args);
  }

}
