/*
 * mvn generated by tentackle-project-archetype.
 */

/**
 * Common stuff not belonging to a certain abstraction level.
 */
module flipkart.common {
  exports flipkart.common;

  requires transitive org.tentackle.pdo;

  provides org.tentackle.common.ModuleHook with flipkart.common.service.Hook;
}
