/*
 * mvn generated by tentackle-project-archetype.
 */

package flipkart.persist.rmi;

import org.tentackle.dbms.rmi.RemoteDbConnection;

/**
 * Interface for the appliction specific connection.
 */
public interface mvnConnection extends RemoteDbConnection {

}
