/*
 * mvn generated by tentackle-project-archetype.
 */

package flipkart.persist.rmi;

import flipkart.pdo.mvnRemoteSession;

import org.tentackle.dbms.rmi.RemoteDbSession;
import org.tentackle.persist.PdoRemoteSessionAdapter;

/**
 * Application specific remote session adapter.
 */
public class mvnRemoteSessionAdapter extends PdoRemoteSessionAdapter implements mvnRemoteSession {

  public mvnRemoteSessionAdapter(RemoteDbSession rs) {
    super(rs);
  }

  @Override
  public mvnRemoteDbSession getRemoteDbSession() {
    return (mvnRemoteDbSession) super.getRemoteDbSession();
  }

}

