/*
 * mvn generated by tentackle-project-archetype.
 */

package flipkart.persist.rmi;

import org.tentackle.dbms.rmi.RemoteDbSession;

/**
 * Interface for the remote session.
 */
public interface mvnRemoteDbSession extends RemoteDbSession {

}