/*
 * mvn generated by tentackle-project-archetype.
 */

package flipkart.pdo.md.domain;

import flipkart.pdo.md.User2Group;

import org.tentackle.pdo.DomainObject;

/**
 * Domain interface for User2Group.
 */
public interface User2GroupDomain extends DomainObject<User2Group> {

}
