/*
 * mvn generated by tentackle-project-archetype.
 */

package flipkart.pdo.md.domain;

import flipkart.pdo.md.User;

/**
 * Domain interface for User.
 */
public interface UserDomain extends OrgUnitDomain<User> {

}
