/*
 * mvn generated by tentackle-project-archetype.
 */

package flipkart.pdo.md.domain;

import flipkart.pdo.md.UserGroup;

/**
 * Domain interface for UserGroup.
 */
public interface UserGroupDomain extends OrgUnitDomain<UserGroup> {

}
