/*
 * mvn generated by tentackle-project-archetype.
 */

/**
 * Desktop FX client module.
 */
module flipkart.client {
  exports flipkart.client;

  requires flipkart.gui;
  requires flipkart.persist;
  requires flipkart.domain;

  requires org.tentackle.fx.rdc;
  requires org.tentackle.fx.rdc.update;

  requires javafx.graphics;
  requires java.rmi;

  provides org.tentackle.common.ModuleHook with flipkart.client.service.Hook;

  // SLF4J isnt a module yet. For some odd reason, we need a lookup scan for deps on the classpath.
  // Otherwise non-modularized deps cannot be located via META-INF/services.
  uses org.tentackle.log.Logger;
}
