/*
 * mvn generated by tentackle-project-archetype.
 */

package flipkart.persist.md.rmi;

import flipkart.pdo.MasterData;
import flipkart.persist.AbstractPersistentMasterData;

import org.tentackle.persist.rmi.AbstractPersistentObjectRemoteDelegate;

/**
 * Base interface for master data remote delegates.
 */
public interface AbstractPersistentMasterDataRemoteDelegate<T extends MasterData<T>,
                                                            P extends AbstractPersistentMasterData<T,P>>
       extends AbstractPersistentObjectRemoteDelegate<T,P> {

}

