/*
 * mvn generated by tentackle-project-archetype.
 */

package flipkart.persist.md.rmi;

import flipkart.pdo.md.OrgUnit;
import flipkart.persist.md.OrgUnitPersistenceImpl;

import org.tentackle.dbms.rmi.RemoteDbSessionImpl;
import org.tentackle.pdo.DomainContext;

import java.rmi.RemoteException;


/**
 * Remote delegate implementation for {@link OrgUnitPersistenceImpl}.
 *
 * @param <T> the pdo interface
 * @param <P> the persistence implementation
 */
public class OrgUnitRemoteDelegateImpl<T extends OrgUnit<T>, P extends OrgUnitPersistenceImpl<T,P>>
       extends AbstractPersistentMasterDataRemoteDelegateImpl<T,P>
       implements OrgUnitRemoteDelegate<T,P>  {


  /**
   * Creates the remote delegate for {@link OrgUnitPersistenceImpl}.
   *
   * @param session the RMI session
   * @param persistenceClass the persistence implementation class
   * @param pdoClass the pdo interface class
   */
  public OrgUnitRemoteDelegateImpl(RemoteDbSessionImpl session, Class<P> persistenceClass, Class<T> pdoClass) {
    super(session, persistenceClass, pdoClass);
  }

  // @wurblet inclrmi Include --missingok .$classname/methods

  //<editor-fold defaultstate="collapsed" desc="code 'inclrmi' generated by wurblet Include">//GEN-BEGIN:inclrmi


  @Override
  public T selectByUniqueDomainKey(DomainContext context, String name) throws RemoteException {
    try {
      return newInstance(context).selectByUniqueDomainKey(name);
    }
    catch (RuntimeException e) {
      throw createException(e);
    }
  }

  //</editor-fold>//GEN-END:inclrmi


}
