/*
 * mvn generated by tentackle-project-archetype.
 */

/**
 * Persistence implementation module.
 */
module flipkart.persist {
  exports flipkart.persist;
  exports flipkart.persist.md;
  exports flipkart.persist.md.rmi;
  exports flipkart.persist.rmi;
  exports flipkart.persist.td;
  exports flipkart.persist.td.rmi;

  requires transitive flipkart.pdo;

  requires transitive org.tentackle.persistence;

  requires java.rmi;

  provides org.tentackle.common.ModuleHook with flipkart.persist.service.Hook;
}
