/*
 * mvn generated by tentackle-project-archetype.
 */

package flipkart.client.service;

import org.tentackle.common.ModuleHook;

import java.util.Locale;
import java.util.ResourceBundle;

/**
 * Hook for the FX client module.
 */
public class Hook implements ModuleHook {

  @Override
  public ResourceBundle getBundle(String baseName, Locale locale) {
    return ResourceBundle.getBundle(baseName, locale);
  }

}
