/*
 * mvn generated by tentackle-project-archetype.
 */

package flipkart.pdo.md.persist;

import flipkart.pdo.md.User;
import flipkart.pdo.md.User2Group;
import flipkart.pdo.md.UserGroup;

import org.tentackle.bind.Bindable;
import org.tentackle.misc.TrackedList;
import org.tentackle.session.Persistent;

/**
 * Persistence interface for UserGroup.
 */
public interface UserGroupPersistence extends OrgUnitPersistence<UserGroup> {

  // @wurblet attributeNames AttributeNames

  //<editor-fold defaultstate="collapsed" desc="code 'attributeNames' generated by wurblet AttributeNames">//GEN-BEGIN:attributeNames


  /** relation name for 'composite list of User2Group nmLinks via User2Group#userGroupId (NmLinks)'. */
  String RN_NMLINKS = "nmLinks";

  //</editor-fold>//GEN-END:attributeNames


  // @wurblet columnLenghts ColumnLengths

//<editor-fold defaultstate="collapsed" desc="code 'columnLenghts' generated by wurblet ColumnLengths">//GEN-BEGIN:columnLenghts


//</editor-fold>//GEN-END:columnLenghts


  // @wurblet methods Methods

//<editor-fold defaultstate="collapsed" desc="code 'methods' generated by wurblet Methods">//GEN-BEGIN:methods


//</editor-fold>//GEN-END:methods


  // @wurblet relations Relations

  //<editor-fold defaultstate="collapsed" desc="code 'relations' generated by wurblet Relations">//GEN-BEGIN:relations


  /**
   * Gets composite list of User2Group nmLinks via User2Group#userGroupId (NmLinks).
   *
   * @return nmLinks NmLinks
   */
  @Bindable
  @Persistent(ordinal=0, comment="NmLinks")
  TrackedList<User2Group> getNmLinks();

  /**
   * Gets list of User joined via composite list of User2Group nmLinks via User2Group#userGroupId (NmLinks).
   *
   * @return list of user
   */
  @Bindable
  @Persistent(ordinal=0, comment="users", component=false)
  TrackedList<User> getUsers();

  /**
   * Returns whether NmLinks is loaded.
   *
   * @return true if getNmLinks() invoked at least once
   */
  @Bindable
  boolean isNmLinksLoaded();

  //</editor-fold>//GEN-END:relations

}
