/*
 * mvn generated by tentackle-project-archetype.
 */

/**
 * FX GUI module.
 */
open module flipkart.gui {
  exports flipkart.gui;
  exports flipkart.gui.main;

  requires flipkart.pdo;

  requires org.tentackle.fx.rdc;

  requires java.desktop;
  requires java.prefs;

  provides org.tentackle.common.ModuleHook with flipkart.gui.service.Hook;
}
