/*
 * mvn generated by tentackle-project-archetype.
 */

/**
 * Domain logic implementation module.
 */
module flipkart.domain {
  exports flipkart.domain;
  exports flipkart.domain.md;
  exports flipkart.domain.td;

  requires transitive flipkart.pdo;

  requires transitive org.tentackle.domain;

  provides org.tentackle.common.ModuleHook with flipkart.domain.service.Hook;
}
