/*
 * mvn generated by tentackle-project-archetype.
 */

package flipkart.gui.about;

import flipkart.gui.GuiBundle;
import javafx.fxml.FXML;
import javafx.scene.Scene;
import javafx.stage.Modality;
import javafx.stage.Stage;

import org.tentackle.fx.AbstractFxController;
import org.tentackle.fx.Fx;
import org.tentackle.fx.FxControllerService;
import org.tentackle.fx.component.FxButton;
import org.tentackle.fx.component.FxLabel;

/**
 * Controller for showing an about dialog.
 */
@FxControllerService
public class AboutView extends AbstractFxController {

  /**
   * Shows the dialog.
   */
  public static void showDialog() {
    AboutView controller = Fx.load(AboutView.class);
    Stage stage = Fx.createStage(Modality.NONE);
    Scene scene = new Scene(controller.getView());
    stage.setScene(scene);
    stage.setTitle(GuiBundle.getString("about"));
    stage.show();
  }



  @FXML
  private FxLabel applicationVersion;
  
  @FXML
  private FxLabel tentackleVersion;

  @FXML
  private FxLabel javaVersion;

  @FXML
  private FxButton closeButton;

  @FXML
  private void initialize() {
    applicationVersion.setText(flipkart.common.Version.RELEASE + " (" + flipkart.common.Version.DATE + ")");
    tentackleVersion.setText(org.tentackle.common.Version.RELEASE + " (" + org.tentackle.common.Version.DATE + ")");
    javaVersion.setText(System.getProperty("java.version"));
    closeButton.setGraphic(Fx.createImageView("close"));
    closeButton.setOnAction(e -> getStage().close());
  }
}
