/*
 * mvn generated by tentackle-project-archetype.
 */

package flipkart.gui.prefs;

import flipkart.common.mvnPreferences;

import org.tentackle.bind.Bindable;
import org.tentackle.fx.AbstractFxController;

/**
 * Base controller class for a preferences tab.
 */
public abstract class AbstractPreferencesTabController extends AbstractFxController {

  @Bindable
  public mvnPreferences getPref() {
    return mvnPreferences.getInstance();
  }

}
