/*
 * mvn generated by tentackle-project-archetype.
 */

package flipkart.gui.prefs;

import javafx.fxml.FXML;

import org.tentackle.fx.FxControllerService;
import org.tentackle.fx.component.FxTextField;

/**
 * Tab for general preferences.
 */
@FxControllerService(binding = FxControllerService.BINDING.BINDABLE_INHERITED)
public class GeneralPreferences extends AbstractPreferencesTabController {

  @FXML
  private FxTextField prefHelpUrl;

}
