/*
 * mvn generated by tentackle-project-archetype.
 */

package flipkart.gui;

import org.tentackle.test.fx.rdc.GuiProviderTest;

/**
 * Tests all GuiProviders.
 */
public class TestGuiProviders extends GuiProviderTest {

  public TestGuiProviders() {
    super("flipkart");
  }

}
